"""
Django settings for backend project.
Generated by 'django-admin startproject' using Django 5.2.6.
"""

from pathlib import Path
import os

# --------------------------------------------
# BASE SETTINGS
# --------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-v-dd=&4^sw4)-q@*vz!9q%$+4%xlm$&d*jfp7ss=z^*6q-sekq'
DEBUG = True
ALLOWED_HOSTS = ["*"]

# --------------------------------------------
# INSTALLED APPS
# --------------------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party
    'rest_framework',
    'import_export',
    'corsheaders',

    # Local apps
    'accounts',
    'main',
    'products',
]

# --------------------------------------------
# MIDDLEWARE (CORS must be at the top)
# --------------------------------------------
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # ✅ must be very first
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

# --------------------------------------------
# TEMPLATES
# --------------------------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'

# --------------------------------------------
# DATABASE
# --------------------------------------------
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "lo_db",
        "USER": "root",
        "PASSWORD": "yashyash21",
        "HOST": "localhost",
        "PORT": "3306",
    }
}

# --------------------------------------------
# PASSWORD VALIDATION
# --------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]

# --------------------------------------------
# INTERNATIONALIZATION
# --------------------------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# --------------------------------------------
# STATIC & MEDIA FILES
# --------------------------------------------
STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = "accounts.CustomUser"

# --------------------------------------------
# EMAIL CONFIG
# --------------------------------------------
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'yashdhawale17@gmail.com'
EMAIL_HOST_PASSWORD = 'aboc xmav bhvp gosb'

# --------------------------------------------
# DJANGO REST FRAMEWORK
# --------------------------------------------
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',  # ✅ for guest cart sessions
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
}

# --------------------------------------------
# CORS SETTINGS (✅ Fixed for frontend)
# --------------------------------------------
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

CORS_ALLOW_CREDENTIALS = True  # ✅ Required for cookies/sessions

# ❌ Remove this line completely (caused your error)
# CORS_ALLOW_ALL_ORIGINS = True


# Razorpay Settings
RAZORPAY_KEY_ID = "rzp_test_Rep4R92qy2KX4H"      
RAZORPAY_KEY_SECRET = "mbr1dDYYKILEbyo6j8NQijFC"
