# Generated by Django 5.2.6 on 2025-11-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_rating_productimage'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='available_sizes',
            field=models.CharField(blank=True, help_text='Comma separated e.g. S,M,L or 6,7,8', max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='size_category',
            field=models.CharField(choices=[('none', 'No sizes'), ('clothing', 'Clothing'), ('shoes', 'Shoes')], default='none', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product', 'size')},
        ),
    ]
